### PR TITLE
collector: beautify warning when include\exclude filters wrong

### LINKED ISSUE #1886: collector should print more descriptive error if found no matches for include/exclude option
Error really not helpful, it should say about typo or not found benchmark, the same for exclude.

```
$ ./target/debug/collector.exe binary_stats +nightly-x86_64-pc-windows-msvc \
    --rustc2 +nightly-x86_64-pc-windows-msvc --include "helloworldasd" --profile Debug --backend Llvm
collector error: Warning: one or more unused --include entries: ["helloworldasd"]
```
See that `include` - `helloworldasd` which is unknown benchmark.

### PR DESCRIPTION
**Pull request by klensy**
Fixes #1886

Instead of:
```
$ ./target/debug/collector.exe binary_stats +nightly-x86_64-pc-windows-msvc \
    --rustc2 +nightly-x86_64-pc-windows-msvc --include "helloworldasd" --profile Debug --backend Llvm
collector error: Warning: one or more unused --include entries: ["helloworldasd"]
```
will print:
```
$ ./target/debug/collector.exe binary_stats +nightly-x86_64-pc-windows-msvc \
    --rustc2 +nightly-x86_64-pc-windows-msvc --include "helloworldasd" --profile Debug --backend Llvm
collector error: Warning: one or more unused --include entries: ["helloworldasd"] found.
Expected zero or more entries or substrings from list: ["await-call-tree", "bitmaps-3.1.0", "cargo-0.60.0", "clap-3.1.6", "coercions", "cranelift-codegen-0.82.1", "ctfe-stress-5", "deep-vector", "deeply-nested-multi", "derive", "diesel-1.4.8", "encoding", "exa-0.10.1", "externs", "futures", "helloworld", "helloworld-tiny", "html5ever", "html5ever-0.26.0", "hyper-0.14.18", "image-0.24.1", "inflate", "issue-46449", "issue-58319", "issue-88862", "libc-0.2.124", "many-assoc-items", "match-stress", "piston-image", "projection-caching", "regex", "regex-1.5.5", "regression-31157", "ripgrep-13.0.0", "ripgrep-13.0.0-tiny", "serde-1.0.136", "serde_derive-1.0.136", "stm32f4-0.14.0", "style-servo", "syn", "syn-1.0.89", "token-stream-stress", "tokio-webpush-simple", "tt-muncher", "tuple-stress", "typenum-1.17.0", "ucd", "unicode-normalization-0.1.19", "unify-linearly", "unused-warnings", "webrender-2022", "wf-projection-stress-65510", "wg-grammar"].
```

First commit reworks include\exclude\exclude_suffix args to be parsed by clap as Vec<String> instead of Option<String> and later manually parsed, second one adds existing bench list to error output.

### CODE REVIEW

File: collector/benchlib/src/benchmark.rs [hunk 1]
```diff
@@ -172,34 +175,58 @@ mod tests {
...
 
     #[test]
     fn test_passes_filter_include() {
-        assert!(!passes_filter("foo", None, Some("bar")));
-        assert!(!passes_filter("foo", None, Some("foobar")));
-
-        assert!(passes_filter("foo", None, Some("f")));
-        assert!(passes_filter("foo", None, Some("foo")));
-        assert!(passes_filter("foo", None, Some("bar,baz,foo")));
+        assert!(!passes_filter("foo", &[], &["bar".to_string()]));
```
Comment (klensy) [inline collector/benchlib/src/benchmark.rs:183]: Ugly.

Comment (klensy) [reply collector/benchlib/src/benchmark.rs:183]: Arg is Vec<String>, so can't be converted to &[&str] inplace, requiring reallocating, except tests :-)

Comment (Kobzol) [reply collector/benchlib/src/benchmark.rs:183]: Yeah, I know. I would still probably do it, since `&[&str]` is more natural to use. The reallocation isn't an important cost here. But let's keep it as it is for now.

File: collector/src/compile/benchmark/mod.rs [hunk 2]
```diff
@@ -504,17 +500,19 @@ pub fn get_compile_benchmarks(
...
+    let check_for_unused = |option, substrings: HashMap<&str, usize>| {
+        if !substrings.is_empty() {
             let unused: Vec<_> = substrings
                 .into_iter()
                 .filter_map(|(i, n)| if n == 0 { Some(i) } else { None })
                 .collect();
             if !unused.is_empty() {
                 bail!(
-                    "Warning: one or more unused --{} entries: {:?}",
+                    "Warning: one or more unused --{} entries: {:?} found.\n\
```
Comment (Kobzol) [inline collector/src/compile/benchmark/mod.rs:511]: Could you please use a multiline string here? (`r#"..."#`). The trailing backslash looks quite weird.

**Review by Kobzol — COMMENTED** [review]
One nit, otherwise LGTM.

File: collector/src/compile/benchmark/mod.rs (hunk 2 above)
Comment (klensy) [reply collector/src/compile/benchmark/mod.rs]: Done.

**Review by Kobzol — APPROVED** [review]
Thank you! :)
