### PR TITLE
Correct sqlite-to-postgres column mapping

### LINKED ISSUE #1827: Incorrect Column Mapping in sqlite-to-postgres
I am encountering an error when attempting to run `site` after migrating via `sqlite-to-postgres`.

### Error Message:
```console
thread 'tokio-runtime-worker' panicked at /workspace/rust-lang/rustc-perf-sqlite2pg/database/src/pool/postgres.rs:617:88:
called `Result::unwrap()` on an `Err` value: "cycles:u is not a codegen backend"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Cause:

It appears the issue is related to a mismatch in column ordering between the sqlite and postgresql.

### PR DESCRIPTION
**Pull request by eth3lbert**
The `backend` column was added later to the `pstat_series` table.
This PR reorders the column order to comply with the schema.

Closes #1827

### CODE REVIEW

**Comment by Kobzol** [comment]
That's interesting. The backend column was indeed added later, but after [this](https://github.com/rust-lang/rustc-perf/blob/ef64e686eedcdb8ea176d04745fe78cca5a4aff9/database/src/pool/sqlite.rs#L379) migration, backend should be before metric. So it probably depends on which version of the SQLite table you have when doing the export.

**Comment by eth3lbert** [comment]
Interesting! What would you expect in this situation? Perhaps adding some columns mapping strategy?

**Comment by eth3lbert** [comment]
Oh wait! In SQLite, the backend column is placed before the metric column. However, in PostgreSQL, it remains after the metric column.

**Comment by Kobzol** [comment]
Oh, good find, I made this error when writing the last migration. It's a PITA to keep these two DB backends in sync.

**Comment by eth3lbert** [comment]
Yep, and it seems somewhat inevitable. I think it would be reasonable to introduce some column mapping to avoid these kinds of issues in the future.

**Comment by Kobzol** [comment]
Yeah, the conversion script should probably be able to support different column order in both backends.

**Comment by eth3lbert** [comment]
Or, we could try passing columns to function`sqlite_attributes` and return a mapped and ordered columns back.
The column names are available through
```sql
select name from PRAGMA_TABLE_INFO('table_name') order by cid
```

**Comment by Kobzol** [comment]
This is a bit outside of my current SQL-fu, but if it works, let's go for it :)

File: database/src/bin/sqlite-to-postgres.rs [hunk 1]
```diff
@@ -56,6 +60,10 @@ impl Table for Artifact {
         "id, name, date, type"
     }
 
+    fn postgres_attributes() -> &'static str {
+        "id, name, date, type"
```
Comment (eth3lbert) [inline database/src/bin/sqlite-to-postgres.rs:64]: Alternatively, we could use a macro to get the field names of the row struct instead of hardcoding them.

**Review by Kobzol — COMMENTED** [review]
This looks reasonable. I assume that the conversion now works for you, after the latest commit?

**Comment by eth3lbert** [comment]
Yes, works as expected.

P.S. I just made some minor wording changes and added information about the panics.

File: database/src/bin/sqlite-to-postgres.rs [hunk 2]
```diff
@@ -193,6 +213,10 @@ impl Table for CollectorProgress {
         "aid, step, start, end"
     }
 
+    fn postgres_attributes() -> &'static str {
```
Comment (Kobzol) [inline database/src/bin/sqlite-to-postgres.rs:216]: Hmm, except for this one table, it seems like all the attribute names are the same. When trying to port this table, the script would crash, is that right?

If that is true, then we basically don't need `postgres_attributes`, right? Since if the names don't match, the code panics, and if they do match, we don't need the new method.

Comment (eth3lbert) [reply database/src/bin/sqlite-to-postgres.rs:216]: Yes, this is the only table that has a different column name from sqlite.  But it wouldn't panic, because it just matches the column names in postgres.

It is also true that if we could ensure all column names are identical between the two databases, then we could just use one from `sqlite_attributes`.  The `postgres_attributes`  is only useful when postgres has a different column name from sqlite that represents the same content.

Comment (Kobzol) [reply database/src/bin/sqlite-to-postgres.rs:216]: Oh, sorry, I didn't realize that the `postgres_columns` logic fixes this. It's a bit complicated, but it works, so let's go with it.

**Review by Kobzol — APPROVED** [review]
