### PR TITLE
Skip doc build-kind on 1.45.0 and lower versions

### LINKED ISSUE #696: Doc build failed on 1.45.0
The beta run succeeded, but 1.45.0 was unable to be benchmarked. I suspect this is because of https://github.com/rust-lang/cargo/pull/8449.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Fixes #696

### CODE REVIEW

File: collector/src/lib.rs [hunk 1]
```diff
@@ -97,6 +97,15 @@ where
     Ok(Option::deserialize(deserializer)?.unwrap_or(0.0))
 }
 
+pub fn version_supports_doc(version_str: &str) -> bool {
+    if let Some(version) = version_str.parse::<semver::Version>().ok() {
+        version >= semver::Version::new(1, 46, 0)
+    } else {
+        assert!(version_str.starts_with("beta") || version_str.starts_with("master"));
```
Comment (jyn514) [inline collector/src/lib.rs:104]: What about `"nightly"`?

Comment (Mark-Simulacrum) [reply collector/src/lib.rs:104]: We don't intend to benchmark nightlies with bench_published (and this matches the incremental check above).
